/* Dandan/OS: v2 interactive shell retained during progressive React migration. */
(() => {
  'use strict';
  if (window.__dandanDesktopMounted) return;
  window.__dandanDesktopMounted = true;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const layer = $('#window-layer');
  const toastBox = $('#toast');
  const appTitles = {
    finder: 'Dandan — Resume', music: 'Music', messages: 'Messages · Dandan',
    notes: 'Notes', photos: 'Photos', terminal: 'Terminal — dandan@macbook',
    dog: '钢镚的档案 ♡', travel: 'Travel Notes', coffee: 'Coffee Diary',
    apex: 'APEX Studio', toolbox: 'Financial Toolbox', writing: 'Stories & People'
  };
  const sizes = {finder:[820,570],music:[790,485],messages:[790,565],notes:[750,520],photos:[860,560],terminal:[750,465],dog:[645,480],travel:[710,530],coffee:[650,465],apex:[770,560],toolbox:[700,520],writing:[650,495]};
  const opened = new Map();
  let z = 1070, soundOn = false;
  let musicPlaying=false, audioCtx=null, musicNodes=[];
  let toastTimer;
  const photos=[
    {src:'/assets/photos/cave-tre-cime.webp',label:'Tre Cime · 岩壁之间',desc:'从岩壁之间看见三峰。时间把海底雕成山。'},
    {src:'/assets/photos/moon-dolomites.webp',label:'Dolomites · 月色',desc:'灰蓝岩壁与玫瑰色天空。'},
    {src:'/assets/photos/cadini-ridge.webp',label:'Cadini · 刀锋般的群峰',desc:'山脊展开，针峰迎面而来。'},
    {src:'/assets/photos/cadini-portrait.webp',label:'Cadini · 向群山走去',desc:'行数十步，豁然开朗。'},
    {src:'/assets/photos/mountain-reflection.webp',label:'Alpine · 片刻停留',desc:'山谷寂静，眼前的石墙有亿万年的时间。'},
    {src:'/assets/photos/hut-terrace.webp',label:'Rifugio · 山屋下午',desc:'路过山屋，给漫长的山路留一段休息时间。'},
    {src:'/assets/photos/sagrada-portrait.webp',label:'Barcelona · 光的建筑',desc:'太阳沿着玫瑰花窗前进，色彩缓慢移动。'},
    {src:'/assets/photos/dandan-gangbeng.webp',label:'Dandan & Gangbeng',desc:'生活里最亲密的陪伴。'},
    {src:'/assets/photos/gangbeng-lap.webp',label:'钢镚 · 好奇',desc:'好奇心和勇气装在很小的身体里。'},
    {src:'/assets/photos/gangbeng-smile.webp',label:'钢镚 · 微笑',desc:'关于那些平常却值得记住的日子。'}
  ];
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function toast(msg){toastBox.textContent=msg;toastBox.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastBox.classList.remove('show'),1300);}
  function announce(msg){if(soundOn) beep();toast(msg);}
  function beep(){try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(880,c.currentTime);o.frequency.exponentialRampToValueAtTime(600,c.currentTime+.1);g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.13);setTimeout(()=>c.close(),300);}catch(e){}}

  const snippets={
    apex:`<div class="simple-app"><span class="eyebrow">CASE STUDY 01 / BANKING × AI</span><h2>APEX Studio <span style="color:#7258e9">✳</span></h2><p><strong>让一线业务经验进入可复用的工作流。</strong></p><p>从客户经理的日常任务出发，梳理资料、事实、规则与审核节点之间的关系，构建提交前作业链的产品原型。</p><div class="app-tags"><span>BANKING × AI</span><span>AGENTS</span><span>SKILLS</span><span>HUMAN REVIEW</span></div><p>围绕授信提交前的资料准备、财报处理、信息查询、融资测算和报告准备等高频步骤，进行任务拆解与工具协作设计。</p><ul><li>业务入口与任务路由：将自然语言需求转换为结构化任务。</li><li>专业 Agent 与 Skills：把经验沉淀为可复用工作流程。</li><li>事实与证据核验：明确数据来源、异常提示、人工复核节点。</li><li>实际工具探索：财报转换、材料清单、业务工具与利率签报。</li></ul><p class="app-meta">MY CONTRIBUTION · 业务需求研究 / 流程架构 / 产品设计 / 原型协同</p><p style="font-size:11px;color:#888">此处为个人经历的公开脱敏介绍，不展示银行内部系统、客户信息和非公开资料。</p></div>`,
    toolbox:`<div class="simple-app"><span class="eyebrow">02 / MAKING REPETITIVE WORK SMALLER</span><h2>Financial Toolbox</h2><p>从财务资料到表格处理，把需要反复核对的细节整理成可以复用的小工具。</p><div class="app-tags"><span>PYTHON</span><span>HTML / CSS / JS</span><span>DATA CLEANING</span><span>WORKFLOWS</span></div><ul><li>通过 Python 辅助处理表格与文档批量任务。</li><li>设计财报格式转换流程，让原始资料更适配系统识别。</li><li>字段匹配、异常提示、数据转换及结果核验。</li><li>结合 Codex、ChatGPT、Claude Code、Muse 与 n8n 开展工作流原型实践。</li></ul><p>AI 是协作工具，关键业务判断仍须由人审核完成。</p><p class="app-meta">PROCESS: OBSERVE → BREAK DOWN → BUILD → VERIFY</p><button class="window-button" data-open="terminal">打开 Terminal 试试 →</button></div>`,
    writing:`<div class="simple-app"><span class="eyebrow">03 / WRITING WITH PURPOSE</span><h2>Stories & People</h2><div class="app-tags"><span>派克说事</span><span>她境 SHEMAP</span><span>EDITORIAL</span></div><p><strong>「派克说事」</strong>研究职场人性、沟通边界与现实博弈。以真实情境为入口，不贩卖空泛技巧。</p><p><strong>「她境 SHEMAP」</strong>面向独立女性，讨论识别风险、自我保护与法律心理的交叉问题。</p><p>文字的价值藏在细节里：一个值得追问的情境、一种可实践的方法，以及读完后仍愿意记住的判断。</p><p class="app-meta">NOTE TO SELF: BE USEFUL. BE SPECIFIC. BE HUMAN.</p></div>`,
    dog:`<div class="simple-app"><span class="eyebrow">HELLO, I'M THE REAL BOSS</span><div class="dog-profile"><img src="/assets/photos/gangbeng-smile.webp" alt="钢镚的肖像摄影"/><div><h2>钢镚 ♡</h2><p>钢镚。十二年里，它一直在场：旅行归来、周末清晨，以及那些平常的日子。</p><p><strong>12 岁 · 小型犬 · 家庭首席幸福官</strong></p><p>最擅长的事情：让普通的一天变得很值得纪念。</p><div class="app-tags"><span>SMALL BUT BRAVE</span><span>GOOD BOY</span><span>♡</span></div></div></div><p class="app-meta">PHOTO NOTE / THE LITTLE COMPANION</p></div>`,
    travel:`<div class="simple-app trip-journal"><span class="eyebrow">A PERSONAL ATLAS / FIELD NOTES</span><h2>山海之间 <span class="trip-star">✳</span></h2><p class="trip-lead">山有地质的时间，城市有人的时间。沿着光线和脚步，把去过的地方重新翻开。</p><div class="trip-tabs" role="tablist" aria-label="旅行故事分类"><button class="selected" data-trip="mountains" role="tab" aria-selected="true">01 山脊</button><button data-trip="hut" role="tab" aria-selected="false">02 山屋</button><button data-trip="cities" role="tab" aria-selected="false">03 城市</button><button data-trip="rainforest" role="tab" aria-selected="false">04 雨林</button><button data-trip="light" role="tab" aria-selected="false">05 光影</button></div>
    <div class="trip-panel selected" data-trip-panel="mountains"><div class="app-hero"><img src="/assets/photos/cadini-ridge.webp" alt="多洛米蒂刀锋群峰与徒步者" /></div><div class="trip-numeral">01 / EARTH & TIME</div><h3>两亿年前，这里曾是海</h3><p>2026 年秋天，我沿着 Seceda 的刀锋山脊漫步，也看过 Cadini 尖锐的群峰和 Tre Cime 沉默的石墙。每行数十步，群峰便换一种形状。两亿多年前这里曾经是海，时间缓慢地把岩石雕成今天的样子。</p><div class="app-tags"><span>SECEDA</span><span>CADINI</span><span>TRE CIME</span></div></div>
    <div class="trip-panel" data-trip-panel="hut"><div class="app-hero"><img src="/assets/photos/moon-dolomites.webp" alt="多洛米蒂月色与玫瑰色天空" /></div><div class="trip-numeral">02 / NIGHT ON THE MOUNTAIN</div><h3>Locatelli，日落之后</h3><p>沿着山路走向 Locatelli 山屋，Tre Cime 在背后变换角度。最想留住的是高海拔山屋的傍晚与清晨：看光线一点一点爬上岩壁，听风和脚步替时间计数。</p><div class="app-tags"><span>RIFUGIO LOCATELLI</span><span>SUNRISE</span><span>SLOW TRAVEL</span></div></div>
    <div class="trip-panel" data-trip-panel="cities"><div class="app-hero"><img src="/assets/photos/sagrada-portrait.webp" alt="圣家堂彩色光影中的人物摄影" /></div><div class="trip-numeral">03 / OLD STONES & STREETS</div><h3>维罗纳，沿着河流走</h3><p>从 Cortina 到 Verona，再到 Milano。我喜欢在维罗纳沿河散步，去看圣泽诺教堂、古老的墓碑和罗马时代的遗迹；也爱那些不需要安排得很满的下午。</p><div class="app-tags"><span>CORTINA</span><span>VERONA</span><span>MILANO</span></div></div>
    <div class="trip-panel" data-trip-panel="rainforest"><div class="trip-numeral">04 / BORNEO · EAST MALAYSIA</div><h3>雨林里的时间尺度</h3><p>《孤独星球》开篇曾问：“你想知道上亿年前雨林的模样吗？”于是来到东马。潮湿的空气、层叠的树冠和不断生长的生命，让时间有了真实的尺度。我们在这片雨林中短暂停留。</p><div class="app-tags"><span>BORNEO</span><span>RAINFOREST</span><span>GEOLOGICAL TIME</span></div></div>
    <div class="trip-panel" data-trip-panel="light"><div class="app-hero"><img src="/assets/photos/sagrada-portrait.webp" alt="圣家堂彩窗里洒下的光" /></div><div class="trip-numeral">05 / BARCELONA · SAGRADA FAMÍLIA</div><h3>太阳在建筑里行走</h3><p>站在圣家堂的柱廊下，蓝紫、金橙与绯红沿着太阳的轨迹移动。透过彩窗，颜色落在石柱、穹顶和地面。这座建筑像森林，会呼吸；每个时刻都有不同的光。</p><div class="app-tags"><span>SAGRADA FAMÍLIA</span><span>GAUDÍ</span><span>LIGHT</span></div></div>
    <p class="trip-note">✳ 山川、光线与脚步之间的私人记录。影像经过艺术调色，故事留下当时的时间与感受。</p><button class="window-button" data-open="photos">OPEN THE PHOTO ROLL →</button></div>`,
    coffee:`<div class="simple-app"><span class="eyebrow">A SMALL DAILY RITUAL</span><h2>Slow coffee ☕</h2><div style="display:grid;grid-template-columns:130px 1fr;gap:25px;align-items:center"><div style="background:#f3dabe;font-size:80px;min-height:140px;display:grid;place-items:center;border-radius:10px">☕</div><div><p>在陌生城市里，我总想找到一家认真烘豆的小店。点一杯手冲，问问豆子的产地、处理法与烘焙思路。</p><p>从产地、处理法到烘焙曲线，细小差别常常藏在一杯咖啡里。</p></div></div><div class="app-tags"><span>POUR OVER</span><span>LIGHT / MEDIUM ROAST</span><span>COFFEE SHOPS</span></div><p class="app-meta">THE BEST MOMENTS ARE SOMETIMES THE QUIET ONES.</p></div>`
  };
  function finderHTML(){return `<div class="finder-layout"><aside class="finder-sidebar"><small>FAVORITES</small><button data-folder="intro" class="selected">▣　About me</button><button data-folder="career">▤　Experience</button><button data-folder="skills">⌘　Skills</button><button data-folder="education">◈　Education</button><button data-folder="projects">✳　Projects</button><p class="sidebar-bottom">DANDAN/OS · PUBLIC EDITION</p></aside><div class="finder-main" id="finder-main"></div></div>`;}
  const finderPages={
    intro:`<div class="file-path">Favorites / Dandan / README.md</div><h2>Hu Xiaodan <span style="color:#a284da">✳</span></h2><p>胡晓丹 · Xiamen, China</p><p>13 年银行从业经历，服务企业融资与科技金融业务，同时探索 AI 工作流、产品原型与知识组织。</p><div class="finder-info"><strong>NOW</strong><span>厦门银行 · 科技业务部 · 对公客户经理</span><strong>INTERESTS</strong><span>AI Agents / 摄影 / 山与湖 / 手冲咖啡 / 钢镚</span><strong>APPROACH</strong><span>Start with real problems. Build things that help.</span></div><button class="window-button" data-folder="career">阅读工作经历 →</button>`,
    career:`<div class="file-path">CAREER / 2013—PRESENT</div><h2>Experience <span style="font-size:13px;font-weight:400;color:#888">· Banking & Enterprise</span></h2><p>从零售与小企业信贷起步，逐步进入科技金融、企业融资与集团客户服务。</p><ul class="finder-list"><li><small>2025.08 — PRESENT</small><b>厦门银行 · 科技业务部</b>对公客户经理；科技与工商客群、集团客户授信、财务分析及风险管理。</li><li><small>2018.09 — 2025.08</small><b>厦门银行 · 梧村支行</b>公司客户经理；小微企业、科技金融、光伏贷与中台流程优化。</li><li><small>2013.07 — 2018.09</small><b>平安银行 · 厦门分行营业部</b>小企业授信、按揭、个人经营与消费信贷。</li></ul>`,
    skills:`<div class="file-path">CAPABILITIES / PRACTICE</div><h2>What I work with</h2><p>Financial analysis / Workflow architecture / Rapid prototyping</p><div><span class="file-chip">Corporate Banking</span><span class="file-chip">Credit Analysis</span><span class="file-chip">Risk Management</span><span class="file-chip">Financial Statements</span><span class="file-chip">Python (基础脚本)</span><span class="file-chip">HTML / CSS / JS</span><span class="file-chip">AI Agents</span><span class="file-chip">Skills / Prompt Design</span><span class="file-chip">n8n Workflows</span><span class="file-chip">Product Prototyping</span></div><p style="margin-top:25px">关注业务场景与技术实现之间的连接：需求梳理、流程设计、快速原型与结果核验。</p>`,
    education:`<div class="file-path">BACKGROUND / EDUCATION</div><h2>Education & Qualifications</h2><ul class="finder-list"><li><small>2009 — 2013</small><b>厦门大学嘉庚学院</b>会计学 · 本科</li><li><small>2007 — 2008</small><b>California State University</b>交流学习</li></ul><p>专业资格：银行业从业资格、初级会计职称、大学英语六级、外贸会计证。</p>`,
    projects:`<div class="file-path">PORTFOLIO / SELECTED WORK</div><h2>Selected Projects</h2><p><strong>APEX Studio</strong> / Banking workflow automation</p><p><strong>Financial Toolbox</strong> / Python & financial document processing</p><p><strong>Stories & People</strong> / Long-form editorial projects</p><div style="display:flex;gap:9px;flex-wrap:wrap"><button class="window-button" data-open="apex">打开 APEX →</button><button class="window-button secondary" data-open="toolbox">Toolbox →</button></div>`
  };
  function notesHTML(){return `<div class="notes-app"><aside class="notes-list"><h3>Notes</h3><button data-note="manifesto" class="selected">✳  A few things</button><button data-note="travels">↗  Places to go</button><button data-note="workflow">⌘  Work notes</button><button data-note="ideas">♡  Little joys</button></aside><article class="notes-editor" id="notes-editor"></article></div>`;}
  const notePages={
    manifesto:`<p class="note-date">2026 · A NOTE TO MYSELF</p><h2>A few things I believe</h2><p>Technology should solve real problems, not just look complicated.</p><p>Good work respects details. Great work respects people.</p><p>Curiosity is a habit worth keeping, even when the calendar is full.</p><p>And sometimes it's okay to close the laptop and go outside.</p>`,
    travels:`<p class="note-date">2026 · JOURNAL</p><h2>A little closer to the mountains</h2><ul><li>Keep the memory of the Seceda ridgeline, Cadini peaks and the Tre Cime morning.</li><li>Find a lake without a crowd.</li><li>Take more photos at sunrise.</li><li>Visit small museums, old bookshops, and historic neighborhoods.</li><li>Make time for a slow coffee.</li></ul>`,
    workflow:`<p class="note-date">2026 · WORKFLOW PRINCIPLES</p><h2>Designing useful AI</h2><ul><li>先定义业务问题，再选工具。</li><li>先核对事实与证据，再组织文字。</li><li>明确哪些环节可以自动化，哪些必须人工审核。</li><li>用真实作业体验衡量工具的价值，保留必要的人工判断。</li></ul>`,
    ideas:`<p class="note-date">SOME ORDINARY MAGIC</p><h2>Little joys</h2><ul><li>钢镚在家等我。</li><li>阳光从云层里漏下来的几分钟。</li><li>一杯刚刚好的手冲。</li><li>在一个陌生城市走进历史。</li><li>把一件反复折腾的小事做成好用的工具。</li></ul>`
  };
  function musicHTML(){return `<div class="music-app"><aside class="music-sidebar"><h2>♫ Music</h2><p>LIBRARY<br/>For You<br/>Browse<br/>Radio</p><hr style="border:0;border-top:1px solid #d8d8d8"><p style="color:#f44b76">♥ Dandan's little mix</p></aside><div class="music-main"><div class="album-stage"><div class="album-cover">✹</div><div><h3>Little Things</h3><p>Dandan's ambient desk mix</p><span style="font-size:11px;color:#999">ORIGINAL SYNTH · NO COPYRIGHTED AUDIO</span></div></div><div class="music-controls"><button data-music="prev" aria-label="上一首">⏮</button><button class="play" data-music="toggle" aria-label="播放或暂停">▶</button><button data-music="next" aria-label="下一首">⏭</button><div class="music-progress"><b></b></div></div><div class="music-track selected"><span>♫</span><strong>Little Things</strong><small>∞</small></div><div class="music-track"><span>♫</span><span>Mountain Air</span><small>∞</small></div><div class="music-track"><span>♫</span><span>Slow Sunday</span><small>∞</small></div><p class="music-disclaimer">点击播放会生成简单的原创环境和弦，不播放原站音乐，也不依赖外部音源。</p></div></div>`;}
  function messagesHTML(){return `<div class="messages-app"><div class="messages-sidebar"><h2>Messages</h2><div class="message-contact"><span class="contact-avatar">D</span><div><b>Dandan / OS</b><small>Public knowledge</small></div></div></div><div class="messages-right"><div class="message-header"><strong>Dandan's digital twin ✳</strong><span>Cloudflare Workers AI · Public knowledge only</span></div><div class="messages-thread" id="messages-thread"><div class="bubble from-bot">你好！我是 Dandan 的网站知识库助手。可以问我她的工作、APEX 项目、技能，或者钢镚和旅行。♡</div><div class="bubble from-bot">试试：“APEX 是什么？”“她做什么工作？”“钢镚是谁？”</div></div><form class="message-compose" id="message-compose"><input aria-label="输入问题" maxlength="300" placeholder="iMessage" autocomplete="off"/><button aria-label="发送消息">↑</button></form><div class="chat-demo-note">WORKERS AI · 聊天问题会发送到本网站的 Cloudflare 后端；请勿输入私人信息</div></div></div>`;}
  function photosHTML(){return `<div class="photos-app"><div class="photos-top"><h2>Through my lens</h2><p>VISUAL ARCHIVE / MOUNTAINS · LIGHT · EVERYDAY LIFE</p></div><p style="font-size:11px;color:#989084">${imgNotice}</p><div class="photos-grid">${photos.map((p,i)=>`<button class="photo-tile" style="--tilt:${[-6,5,-3,7,-4,3][i]}deg" data-image="${i}"><img src="${p.src}" alt="${escapeHtml(p.label)}"/><span>${escapeHtml(p.label)}</span></button>`).join('')}</div></div>`;}
  function terminalHTML(){return `<div class="terminal-app" id="terminal-main"><div>DANDAN/OS 1.0 (browser runtime)</div><div>Welcome to Dandan's little universe.</div><div>Type <span class="reply">help</span> to see available commands.</div><br/><div id="terminal-history"><div><span class="prompt">dandan</span>@MacBook-Pro <span class="path">~</span> &gt; whoami</div><div class="reply">Hu Xiaodan (Dandan) — banking × AI × curiosity</div><br/></div><form class="terminal-row" id="terminal-form"><span><span class="prompt">dandan</span>@MacBook-Pro <span class="path">~</span> &gt;</span><input aria-label="终端命令" spellcheck="false" autocapitalize="off" autocomplete="off" /></form></div>`;}
  function appHTML(name){if(name==='finder')return finderHTML();if(name==='notes')return notesHTML();if(name==='music')return musicHTML();if(name==='messages')return messagesHTML();if(name==='photos')return photosHTML();if(name==='terminal')return terminalHTML();return snippets[name]||'<div class="simple-app"><h2>Coming soon</h2></div>';}
  function focusWindow(el){z++;el.style.zIndex=z;for(const w of opened.values())w.classList.toggle('focused',w===el);}
  function dockState(){for(const btn of $$('.dock-app'))btn.classList.toggle('is-open',opened.has(btn.dataset.open));}
  function openApp(name){if(!appTitles[name])return;const existing=opened.get(name);if(existing){existing.classList.remove('is-min');focusWindow(existing);if(name==='terminal')$('#terminal-form input',existing)?.focus();return;}
    const [w,h]=sizes[name];const el=document.createElement('section');el.className=`desktop-window ${name==='terminal'?'dark':''}`;el.setAttribute('role','dialog');el.setAttribute('aria-label',appTitles[name]);el.dataset.app=name;el.style.setProperty('--window-width',w+'px');el.style.setProperty('--window-height',h+'px');el.innerHTML=`<header class="window-titlebar"><div class="traffic"><button class="close" data-win="close" aria-label="关闭窗口" title="关闭"></button><button class="minimize" data-win="min" aria-label="最小化" title="最小化"></button><button class="maximize" data-win="max" aria-label="最大化" title="最大化"></button></div><span>${escapeHtml(appTitles[name])}</span><small class="window-title-right">DANDAN/OS</small></header><div class="window-body">${appHTML(name)}</div>`;
    layer.append(el);opened.set(name,el);focusWindow(el);dockState();
    if(window.innerWidth>750){
      const offset=(opened.size-1)%5*27;
      if(name==='music'){el.style.left='max(22px, 3vw)';el.style.top='max(62px, 11vh)';}
      else if(name==='terminal'){el.style.left=`max(12px, calc(100vw - ${w}px - 25px))`;el.style.top='51px';}
      else if(name==='messages'){el.style.left=`max(16px, calc(50vw - ${w*.54}px))`;el.style.top=`max(55px, calc(50dvh - ${h*.26}px))`;}
      else {el.style.left=`max(12px, calc(50vw - ${w/2}px + ${offset}px))`;el.style.top=`max(45px, calc(50dvh - ${h/2}px - 5px + ${offset}px))`;}
    }
    installDragging(el);initializeApp(name,el);updateNav();announce(`${appTitles[name]} opened`);
  }
  function closeApp(name){const el=opened.get(name);if(!el)return;el.remove();opened.delete(name);dockState();updateNav();if(name==='music')stopMusic();}
  function minimizeApp(name){const el=opened.get(name);if(!el)return;el.classList.add('is-min');}
  function maxApp(name){const el=opened.get(name);if(!el)return;el.classList.toggle('is-max');focusWindow(el);}
  function installDragging(el){const bar=$('.window-titlebar',el);let drag=null;bar.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button')||window.innerWidth<=750||el.classList.contains('is-max'))return;const rect=el.getBoundingClientRect();drag={x:e.clientX-rect.left,y:e.clientY-rect.top};bar.setPointerCapture(e.pointerId);focusWindow(el);e.preventDefault();});bar.addEventListener('pointermove',e=>{if(!drag)return;el.style.left=Math.max(0,Math.min(window.innerWidth-el.offsetWidth,e.clientX-drag.x))+'px';el.style.top=Math.max(38,Math.min(window.innerHeight-110,e.clientY-drag.y))+'px';});const stop=()=>drag=null;bar.addEventListener('pointerup',stop);bar.addEventListener('lostpointercapture',stop);bar.addEventListener('dblclick',e=>{if(!e.target.closest('button'))maxApp(el.dataset.app)});el.addEventListener('pointerdown',()=>focusWindow(el));}
  function initializeApp(name,root){if(name==='finder'){setFinder('intro',root);}if(name==='notes'){setNote('manifesto',root);}if(name==='messages'){const form=$('#message-compose',root);form.addEventListener('submit',e=>{e.preventDefault();const input=$('input',form);const query=input.value.trim();if(!query)return;const thread=$('#messages-thread',root);addBubble(thread,query,true);input.value='';(async()=>{const button=$('button',form);button.disabled=true;
      try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:query})});
        const data=await response.json(); if(!response.ok)throw new Error(data.error||'AI 暂时不可用');
        if(opened.get('messages')===root)addBubble(thread,String(data.answer||'暂时没有回答'),false);
      }catch(error){if(opened.get('messages')===root)addBubble(thread,'目前未连接在线 AI（'+String(error.message||'请求失败')+'）。以下是本地公开知识库答案：\n'+answerQuestion(query),false);}
      finally{button.disabled=false;}})();});}
    if(name==='terminal'){$('#terminal-form',root).addEventListener('submit',e=>{e.preventDefault();const input=$('#terminal-form input',root);const command=input.value.trim();input.value='';runTerminal(command,root);});setTimeout(()=>$('#terminal-form input',root)?.focus(),160);}}
  function setFinder(page,root){if(!finderPages[page])return;$('#finder-main',root).innerHTML=finderPages[page];$$('[data-folder]',root).forEach(b=>b.classList.toggle('selected',b.dataset.folder===page));}
  function setNote(page,root){if(!notePages[page])return;$('#notes-editor',root).innerHTML=notePages[page];$$('[data-note]',root).forEach(b=>b.classList.toggle('selected',b.dataset.note===page));}
  function addBubble(thread,msg,isUser){const bubble=document.createElement('div');bubble.className='bubble '+(isUser?'from-user':'from-bot');bubble.textContent=msg;thread.append(bubble);thread.scrollTop=thread.scrollHeight;}
  function answerQuestion(q){const v=q.toLowerCase();if(/钢镚|狗|吉娃娃|gangbeng|pet|dog/.test(v))return '钢镚是一只 12 岁的吉娃娃，是 Dandan 家里的首席幸福官。网站里有经过艺术调色的钢镚照片。点击 Dock 上的狗狗图标就能看到！';if(/apex|智能体|agent|项目|创新|skills/.test(v))return 'APEX Studio 是 Dandan 发起的授信作业 AI 工作流探索项目，关注资料准备、财报处理、信息查询、任务路由、Skills 协作、事实核验与人工复核。更多细节可以打开 Projects → APEX。';if(/工作|银行|职业|简历|银行家|bank|resume|金融|信贷/.test(v))return 'Dandan 目前在厦门银行科技业务部从事对公客户经营，涉及科技企业授信、财务与风险分析、项目落地等工作。她也在研究怎样用 AI 减少重复劳动。可以打开 Resume 阅读公开版简历。';if(/python|编程|代码|技能|技术|自动化|n8n|tool/.test(v))return '她使用 Python 基础脚本、HTML/CSS/JavaScript、AI 编程工具和自动化工作流来制作业务工具与交互原型。擅长从真实业务中提炼需求与核验规则。';if(/旅行|旅游|多洛米蒂|意大利|dolomites|travel|摄影|photo|拍照|seceda|cadini|tre cime|locatelli/.test(v))return '她曾去到多洛米蒂、东马雨林和巴塞罗那的圣家堂；2026 年秋天在 Seceda、Cadini、Tre Cime 和 Locatelli 山屋留下了照片。她尤其喜欢山脊、日出、森林和有历史的街道；你可以打开 Travel 查看三章旅行手账。';if(/咖啡|coffee|手冲/.test(v))return '她喜欢手冲咖啡，关心烘焙风味、咖啡豆和那些认真做一杯咖啡的小店。她的 Coffee Diary 在 Dock 右边。';if(/写作|派克|她境|公众号|文章/.test(v))return '她还做写作实验：「派克说事」探讨职场沟通与人性，「她境 SHEMAP」关注女性自我保护。希望内容能带给读者实际帮助。';if(/你好|hello|hi|hey|在吗/.test(v))return '你好呀！👋 我可以介绍 Dandan 的工作、APEX、AI 技能、旅行、咖啡或者钢镚。';return '我仅根据公开资料介绍 Dandan 的经历和爱好。可以试试问我“APEX 是什么？”或“钢镚是谁？”。';}
  const terminalCommands={help:'AVAILABLE COMMANDS\n  whoami  — About Dandan\n  skills  — Skills & workflow\n  work    — Career summary\n  apex    — APEX Studio\n  hobbies — Off-the-clock life\n  dog     — The real boss\n  date    — Local time\n  clear   — Clear terminal\n  open <app> — e.g. open photos',whoami:'Hu Xiaodan · Dandan\nCorporate banker + AI workflow enthusiast\nBased in Xiamen, China.',skills:'Banking • Credit Analysis • Python basics\nHTML/CSS/JS • AI Agents • Prompt & Skills\nn8n • Workflow Design • Human Review',work:'2025–now  Xiamen Bank · Technology Business\n2018–2025 Xiamen Bank · Wucun Branch\n2013–2018 Ping An Bank · Xiamen',apex:'APEX Studio: Business workflow → agents → Skills → verification.\nA project about making everyday banking tasks easier.',hobbies:'Photography / Dolomites / historic streets / coffee / Gangbeng ♡',dog:'woof! 🐾 The chief happiness officer is a 12-year-old Chihuahua.'};
  function runTerminal(cmd,root){if(!cmd)return;const history=$('#terminal-history',root),terminal=$('#terminal-main',root);const row=document.createElement('div');const mark=document.createElement('span');mark.className='prompt';mark.textContent='dandan';row.append(mark,document.createTextNode('@MacBook-Pro ~ > '+cmd));history.append(row);if(cmd.toLowerCase()==='clear'){history.replaceChildren();return;}const response=document.createElement('div');response.className='reply';const key=cmd.toLowerCase().trim();if(key==='date')response.textContent=new Date().toString();else if(key.startsWith('open ')){const which=key.split(/\s+/)[1];if(appTitles[which]){response.textContent=`Opening ${which}...`;openApp(which)}else response.textContent=`Unknown app: ${which}`;}else if(key==='ls')response.textContent='apps/  projects/  photos/  README.md';else if(key==='pwd')response.textContent='/Users/dandan';else response.textContent=terminalCommands[key]||`Command not found: ${cmd}. Try 'help'.`;history.append(response,document.createElement('br'));terminal.scrollTop=terminal.scrollHeight;}
  function startMusic(){if(musicPlaying)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const freqs=[130.81,164.81,196.00,261.63];const master=audioCtx.createGain();master.gain.value=.045;master.connect(audioCtx.destination);freqs.forEach((hz,i)=>{const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.type=i%2?'sine':'triangle';osc.frequency.value=hz;gain.gain.value=i===0?.19:.11;osc.connect(gain).connect(master);osc.start();musicNodes.push(osc);});musicNodes.push(master);musicPlaying=true;$$('[data-music="toggle"]').forEach(b=>b.textContent='⏸');$$('.music-progress b').forEach(b=>b.style.width='67%');}catch(e){toast('当前浏览器不支持音频播放。');}}
  function stopMusic(){if(!musicPlaying)return;musicNodes.forEach(node=>{try{node.stop?.();node.disconnect?.()}catch(e){}});musicNodes=[];musicPlaying=false;$$('[data-music="toggle"]').forEach(b=>b.textContent='▶');$$('.music-progress b').forEach(b=>b.style.width='18%');}
  function openImage(index){const item=photos[index];if(!item)return;const box=$('#lightbox');$('img',box).src=item.src;$('img',box).alt=item.label;$('span',box).textContent=item.label+' · '+item.desc;box.hidden=false;}
  function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});}
  function updateNav(){const menu=$('.menubar');menu.classList.toggle('is-light',window.scrollY>window.innerHeight*.55);$('.dock-wrap').classList.toggle('is-hidden',window.scrollY>document.getElementById('welcome').offsetHeight*.8&&opened.size===0);let section='welcome';for(const id of ['welcome','about','projects','life']){const el=document.getElementById(id);if(el.getBoundingClientRect().top<window.innerHeight*.4)section=id;}$$('.nav-link').forEach(link=>link.classList.toggle('active',link.getAttribute('href')==='#'+section));}
  document.addEventListener('click',e=>{const winButton=e.target.closest('[data-win]');if(winButton){const owner=winButton.closest('.desktop-window');if(owner){const n=owner.dataset.app;({close:closeApp,min:minimizeApp,max:maxApp})[winButton.dataset.win](n);}return;}
    const tripButton=e.target.closest('[data-trip]');if(tripButton){const root=tripButton.closest('.desktop-window');if(root){$$('[data-trip]',root).forEach(b=>{const active=b.dataset.trip===tripButton.dataset.trip;b.classList.toggle('selected',active);b.setAttribute('aria-selected',String(active));});$$('[data-trip-panel]',root).forEach(p=>p.classList.toggle('selected',p.dataset.tripPanel===tripButton.dataset.trip));}return;}
    const folder=e.target.closest('[data-folder]');if(folder){const root=folder.closest('.desktop-window');if(root)setFinder(folder.dataset.folder,root);return;}
    const note=e.target.closest('[data-note]');if(note){const root=note.closest('.desktop-window');if(root)setNote(note.dataset.note,root);return;}
    const imageButton=e.target.closest('[data-image]');if(imageButton){openImage(Number(imageButton.dataset.image));return;}
    const musicButton=e.target.closest('[data-music]');if(musicButton){const action=musicButton.dataset.music;if(action==='toggle'){musicPlaying?stopMusic():startMusic()}else announce('This ambient mix is a single original looping composition.');return;}
    const opener=e.target.closest('[data-open]');if(opener){openApp(opener.dataset.open);return;}
    const scroller=e.target.closest('[data-scroll]');if(scroller){document.getElementById(scroller.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return;}
    if(e.target.closest('.lightbox-close')||e.target.id==='lightbox')$('#lightbox').hidden=true;
  });
  $('#sound-button').addEventListener('click',()=>{soundOn=!soundOn;$('#sound-button').textContent=soundOn?'♫':'♩';toast(soundOn?'系统提示音开启':'系统提示音关闭')});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#lightbox').hidden){$('#lightbox').hidden=true;return;}const win=[...opened.values()].sort((a,b)=>Number(b.style.zIndex)-Number(a.style.zIndex))[0];if(win)closeApp(win.dataset.app);}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openApp('terminal');}});
  const obs=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');obs.unobserve(x.target);}}),{threshold:.08});$$('.reveal').forEach(x=>obs.observe(x));
  window.addEventListener('scroll',updateNav,{passive:true});window.addEventListener('resize',updateNav);updateClock();setInterval(updateClock,30_000);updateNav();
  if(location.hash&&['#about','#projects','#life'].includes(location.hash))setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView(),150);
  console.info('%c DANDAN/OS v3.0 \n%c Built for curious people.','color:#58a3ff;font-weight:bold;font-size:20px','font-size:12px');
})();
